<?php

namespace ContainerBY3GXSi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBatchActionDtoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.J5VAo3U.EasyCorp\Bundle\EasyAdminBundle\Dto\BatchActionDto' shared service.
     *
     * @return \EasyCorp\Bundle\EasyAdminBundle\Dto\BatchActionDto
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.J5VAo3U": it references class "EasyCorp\\Bundle\\EasyAdminBundle\\Dto\\BatchActionDto" but no such service exists.');
    }
}
