<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBY3GXSi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBY3GXSi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBY3GXSi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBY3GXSi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBY3GXSi\App_KernelDevDebugContainer([
    'container.build_hash' => 'BY3GXSi',
    'container.build_id' => '6380b668',
    'container.build_time' => 1655217582,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBY3GXSi');
